### ISSUE TITLE
It is possible for motions to just exceed the max/min ranges

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#33]
Joystick motions can cause the sample position to exceed the motion range by a few microns (e.g. 50 microns). The axis is then out of range and it is no longer possible to move it with the joystick. It can only be returned using the on-screen buttons. 

I'm on the `master` branch.

**Comment by raacampbell** [comment]
This happened again today and confused a user. Today the max X pos was +30,000 µm. Somehow a joystick motion got it to +30,150 µm. At this point it locked itself because all motions were out of bounds. This is because the step size was 100 µm and so even one step in the correct direction is out of bounds. I set the step size to 200 µm and it moved to 29,950 µm and now is happy.

**Comment by raacampbell** [comment]
I just heard from a user that it was the via the on-screen buttons that the stages entered an out of range position.

**Comment by nvladimus** [comment]
The issue with on-screen buttons is due to slow PI stages, use can click much faster than stages can move. Solved on GUI side by adding [`'button_sleep_ms_xyzft'`](https://github.com/mesoSPIM/mesoSPIM-control/blob/972f834156286a5f3801084ed3271632af08d740/mesoSPIM/config/demo_config.py#L22) config parameter to slow down clicking the stage control buttons.
