### ISSUE TITLE
hdf5 / image processing

### ISSUE THREAD

**Issue by spagess** [mesoSPIM/mesoSPIM-control#60]
We just installed the last stable version and found out that the automatic image processing is not working when .h5 is choosen as an outpout format.

**Comment by nvladimus** [comment]
What automatic image processing do you use?

**Comment by spagess** [comment]
max projection ...

**Comment by nvladimus** [comment]
This feature was commented out by Fabian at some point, because it was non-performant for large datasets. I've added it back in [7c90c64](https://github.com/mesoSPIM/mesoSPIM-control/commit/7c90c64b94f59886fd71914816045844551f8ec9). It works when output format is either `.tiff` or `.raw`, by incrementally computing MAX projection of each tile/channel, with virtually no computing overhead. It does not make much sense for `.h5` format, because this would require generation of file name list just for MAX projection files, and lead to clutter in the output folder. With `.h5` file one can simply drag and drop into BigStitcher or Imaris and quickly preview the  dataset anyway. I hope this resolves the issue.

**Comment by ffvoigt** [comment]
In general, it would be very useful to have max projections for hdf5 as well - the use case is that it is really convienient to start some simple processing right after the aquisition to streamline data-quality checks. One idea would be to provide a kind of script "hook" that would allow users to specify their own image processing script that get executed either after each stack or after the whole acquisition is complete. This would also help users who want some form of custom compression. 

-----"Nikita Vladimirov" ***@***.***> schrieb: -----
An: "mesoSPIM/mesoSPIM-control" ***@***.***>
Von: "Nikita Vladimirov" ***@***.***>
Datum: 22.07.2021 14:32
Kopie: "Subscribed" ***@***.***>
Betreff: Re: [mesoSPIM/mesoSPIM-control] hdf5 / image processing (#60)


 This feature was commented out by Fabian at some point, because it was non-performant for large datasets. I've added it back in 7c90c64. It works when output format is either .tiff or .raw, by incrementally computing MAX projection of each tile/channel, with virtually no computing overhead. It does not make much sense for .h5 format, because this would require generation of file name list just for MAX projection files, and lead to clutter in the output folder. With .h5 file one can simply drag and drop into BigStitcher or Imaris and quickly preview the  dataset anyway. I hope this resolves the issue.
